site_name: 'python-app-new-3 API Documentation'
site_description: 'Main documentation for python-app-new-3 APIs'
repo_url: https://github.com/learners-codetree/python-app-new-3
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting Started: 'docs/index.md'